<?php

/**
 * @file
 */

declare(strict_types=1);

/**
 * @file
 * Install, update and uninstall functions for the MET Tide Data module.
 */

/**
 * Implements hook_install().
 */
function met_tide_data_install(): void {
  \Drupal::messenger()->addStatus(t('Module MET Tide Data has been installed.'));
}

/**
 * Implements hook_uninstall().
 */
function met_tide_data_uninstall(): void {
  \Drupal::messenger()->addStatus(t('Module MET Tide Data has been uninstalled.'));
}
