<?php

/**
 * @file
 * Contains eopts.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function eopts_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the eopts module.
    case 'help.page.eopts':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('eopts general module, included by default from template') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function eopts_theme() {
  return [
    'eopts' => [
      'render element' => 'children',
    ],
  ];
}
